name: build-publish-python-deploy-image
on:
  workflow_dispatch:
  schedule:
  - cron: '0 1 17 * *' # noon 1:00 pm on 17th of every month

run-name: build-publish-python-deploy-image
jobs:
  build-publish-python-deploy-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and docker image with tag
      uses: docker/build-push-action@v5
      with:
        file: python/Dockerfile
        load: true
        push: false
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-slave-python-image:latest

    - name: List files
      run: ls -la

    - name: Build and docker image with latest tag
      uses: docker/build-push-action@v5
      with:
        file: python/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-slave-python-image:latest

    - name: Build wand docker image with tag
      uses: docker/build-push-action@v6
      with:
        file: python/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-slave-python-image:3.13.5

    - name: set up docker and scan docker image for vulnerabilities
      uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x
        docker version
        docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-slave-python-image:latest
